name: CI Workflow
on:
    push:
        branches:
            - main
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo code
              uses: actions/checkout@v4
    setup: 
        runs-on: ubuntu-latest
        steps:
            - name: Setup my node environment
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Run tests
              run: npm test
